version: '3.8'
services:
  dev-db-postgres:
    image: postgres:16.1
    container_name: dev-db-postgres
    hostname: dev-db-postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    hostname: redis
    restart: always
    