version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5434 #{post in host(myPC)} : #{post in container}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - nestjs-network
networks:
  nestjs-network:
#Create container, network, ... form "docker compose" file:
#-d: background mode
#docker compose up -d (detach mode)